### ISSUE TITLE
Register Button not working

### ISSUE THREAD

**Issue by Albotoss** [bitcoinbrisbane/bitcoinpokertour#112]
After I have added my username, email and btc address the register button is non responsive

**Comment by bitcoinbrisbane** [comment]
@Albotoss what data did you use? It works for me.

**Comment by Albotoss** [comment]
![Screenshot_20240812_095021_Brave](https://github.com/user-attachments/assets/a39c7e1f-facd-495a-a12c-34d18a869cbc)

**Comment by Albotoss** [comment]
Tried on my PC and my tablet. I used Brave browser.

**Comment by Albotoss** [comment]
tried 2 more addresses still doesnt work.
