### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by TexasHODL** [bitcoinbrisbane/bitcoinpokertour#15]
Home page, add content.
-Coming soon!! (Under Welcome)
-Link to Telegram group to register interest in 'Block Zero' event (https://t.me/+4_ll8Wiu8zQ0MTE9)
-more details on event to be added later
-Add a count down timer

**Comment by bitcoinbrisbane** [comment]
Maybe a count down to the event 0 once we know the date?  Maybe a new ticket for this.

**Comment by bitcoinbrisbane** [comment]
Count down examples https://medium.com/geekculture/23-javascript-countdown-timer-for-website-273efc2f5618

**Comment by TexasHODL** [comment]
![photo_2024-06-13_13-21-14](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/169858872/b580b3e5-6109-4ea1-b23d-c7b2f10089da)
