### ISSUE TITLE
Fix bottom links on home page

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bitcoinpokertour#18]
These bottom cards should go to the correct route.

<img width="1018" alt="image" src="https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/8411406/92878032-d374-4c51-a684-3c284754ce31">

**Comment by ManyRios** [comment]
All of these issues can be solved ASAP

**Comment by rishab-bisht** [comment]
what are the routes for 'Buy bitcoin' and 'Inscription' ?

**Comment by rishab-bisht** [comment]
i have changed the routes for 'Event' and 'Register'
if you want i can raise a pull request for that

**Comment by bitcoinbrisbane** [comment]
> i have changed the routes for 'Event' and 'Register' if you want i can raise a pull request for that

Ok great.  Yes please

**Comment by bitcoinbrisbane** [comment]
> what are the routes for 'Buy bitcoin' and 'Inscription' ?

/about/buybitcoin
/inscriptions

Those should do for now
