### ISSUE TITLE
Add menu items

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bitcoinpokertour#2]
Nav menu needs to be flat.  Home, Schedule, Promotions, Treasury, Bitcoin Guide, Contact

![image](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/8411406/769fab1d-c20f-4b7b-b898-1b543a1405e7)

**Comment by Adonai-Technologies** [comment]
Please assign this to me

**Comment by ManyRios** [comment]
Hey @bitcoinbrisbane let's chat in LabX

**Comment by bitcoinbrisbane** [comment]
> Please assign this to me

Done.

**Comment by bitcoinbrisbane** [comment]
> Hey @bitcoinbrisbane let's chat in LabX



> Hey @bitcoinbrisbane let's chat in LabX

Sure.  Im just waiting on feedback from the team.

**Comment by ManyRios** [comment]
> > Hey @bitcoinbrisbane let's chat in LabX
> 
> > Hey @bitcoinbrisbane let's chat in LabX
> 
> Sure. Im just waiting on feedback from the team.

It's ok you already assign this to other contributor.... thx

**Comment by bitcoinbrisbane** [comment]
> > > Hey @bitcoinbrisbane let's chat in LabX
> > 
> > 
> > > Hey @bitcoinbrisbane let's chat in LabX
> > 
> > 
> > Sure. Im just waiting on feedback from the team.
> 
> It's ok you already assign this to other contributor.... thx

Well he's offered to do this gratis.  We are going to hire the LaborX person too, probably tomorrow.

**Comment by ManyRios** [comment]
> > > > Hey @bitcoinbrisbane let's chat in LabX
> > > 
> > > 
> > > > Hey @bitcoinbrisbane let's chat in LabX
> > > 
> > > 
> > > Sure. Im just waiting on feedback from the team.
> > 
> > 
> > It's ok you already assign this to other contributor.... thx
> 
> Well he's offered to do this gratis. We are going to hire the LaborX person too, probably tomorrow.

Ok... Thx

**Comment by bitcoinbrisbane** [comment]
Fixed in PR #16

**Comment by bitcoinbrisbane** [comment]
@Adonai-Technologies thanks for that, however we will need to get rid of the "new tab" button

<img width="889" alt="image" src="https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/8411406/4ec94ec5-3a68-496b-bf39-4ea16c4d3015">

**Comment by bitcoinbrisbane** [comment]
@ManyRios let's finish this guy off.  Seems all the tabs are grey on selection.
