### ISSUE TITLE
Menu on mobile 

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bitcoinpokertour#24]
![image](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/8411406/6cb2fd29-b29a-41ac-8bc6-e453048f037d)

**Comment by ManyRios** [comment]
New Feature: Add a hamburger button for mobile view

**Comment by bitcoinbrisbane** [comment]
@ManyRios still not correct.  If you collapse then expand on desktop the menu doesn't go back

![image](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/8411406/58266b93-1336-415e-98cf-800e0b8b7b11)

**Comment by ManyRios** [comment]
> @ManyRios still not correct. If you collapse then expand on desktop the menu doesn't go back
> 
> ![image](https://private-user-images.githubusercontent.com/8411406/340138279-58266b93-1336-415e-98cf-800e0b8b7b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NzYzMTAsIm5iZiI6MTcxODU3NjAxMCwicGF0aCI6Ii84NDExNDA2LzM0MDEzODI3OS01ODI2NmI5My0xMzM2LTQxNWUtOThjZi04MDBlMGI4YjdiMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTZUMjIxMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZjY2I4MzNmZjdlNmZkZmJkODgzMDUzNjUxYzE2OThhOGI2ZDk0ZTRkY2I4Y2Q3YzBlOWQ4OWYzOTA0ZDE2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kMOGkGJ7gdIaSKJ5QBrqgMTUhvPnwikWvVTnlqxxUho)


The fix will be uploaded in the next PR 

https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/34518489/d5e2a275-7a71-4c9c-ade4-e667bbfec351

**Comment by ManyRios** [comment]
This one is fixed in this PR https://github.com/bitcoinbrisbane/bitcoinpokertour/pull/32
