### ISSUE TITLE
Contacts page

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bitcoinpokertour#3]
* Create /contacts route and page
* Content not required, this will be added later

**Comment by TexasHODL** [comment]
Add a contact section on the about page with a contact form to become a sponsor/affiliate

**Comment by bitcoinbrisbane** [comment]
Changing this to contacts page.

**Comment by bitcoinbrisbane** [comment]
> Add a contact section on the about page with a contact form to become a sponsor/affiliate

Sponsor / affiliate defined in #9

**Comment by ManyRios** [comment]
Fixed in PR https://github.com/bitcoinbrisbane/bitcoinpokertour/pull/37
