### ISSUE TITLE
Mobile home page

### ISSUE THREAD

**Issue by TexasHODL** [bitcoinbrisbane/bitcoinpokertour#33]
-Resize/change margins for "Welcome to the Bitcoin Poker Tour" so it doesn't stretch so far down the screen.

**Comment by ManyRios** [comment]
Fixed in PR https://github.com/bitcoinbrisbane/bitcoinpokertour/pull/37

**Comment by ManyRios** [comment]
@TexasHODL  Something wrong?

**Comment by TexasHODL** [comment]
The welcome message needs to be stretched out a bit. Its too slim, there is so much empty space on the sides of the screen

**Comment by ManyRios** [comment]
Please leave here an image explaining better what do you want

**Comment by TexasHODL** [comment]
![mobile home](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/169858872/65834f7f-1831-40f1-9927-0fabfcf32d83)
With the telegram link as well. Looks like the telegram link has dissapeared from the home page to

**Comment by ManyRios** [comment]
![image](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/34518489/8f8afa69-f77c-458c-b2ba-3807a7f83edb)

**Comment by TexasHODL** [comment]
I think the telegram link under coming soon was better

**Comment by ManyRios** [comment]
![image](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/34518489/293c80ec-3c4d-4d31-88fb-4d540e1f9c35)

**Comment by TexasHODL** [comment]
ok leave it at that for now then
