### ISSUE TITLE
BTCPT Logo

### ISSUE THREAD

**Issue by TexasHODL** [bitcoinbrisbane/bitcoinpokertour#43]
- Increase the size of the Logo pinned to each page to fill the space a bit more, like the image below
![Untitled](https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/169858872/46edf528-8d60-49c1-92a6-042ddb50b359)

**Comment by ManyRios** [comment]
Fixed in PR https://github.com/bitcoinbrisbane/bitcoinpokertour/pull/53
