### ISSUE TITLE
Event -> Register

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bitcoinpokertour#6]
Create a form that posts the the api with the fields 

* nickname or bns https://btc.us
* full_name (not required) for hendon mob stats
* email
* bitcoin_address (for their payouts)
* country (not required)
* event_id (from query string)

HTTP POST /registration

```json
{
    "name": "Dog",
    "email": "dog4@dog.com",
    "bitcoin_address": "bc1qynm3qsqhqsw5vd44p0u9mjsta6cpzdutwpldvx"
}
```

response
```json
{
    "name": "Dog",
    "email": "dog4@dog.com",
    "date": "2024-06-04T05:06:45.793Z",
    "event_id": "665e8fcc4666b3aebb756774",
    "_id": "665ea0e5f5e1050635906e2e",
    "__v": 0,
    "bitcoin_address": "tb1qugnsszut6dm6ggj8ut45tg83tklfcsqwv4l39q"
}
```

That returns a bitcoin address for them to pay.

This should also send a unique link for them to click and confirm their email.  Not critical, but to stop spam.  The link should be a HMAC with the mongo `_id` included.

**Comment by bitcoinbrisbane** [comment]
Re opening issue.  Not working.  Ill try with postman to test.

**Comment by ManyRios** [comment]
Fixed...?
