### ISSUE TITLE
Event -> Event details

### ISSUE THREAD

**Issue by bitcoinbrisbane** [bitcoinbrisbane/bitcoinpokertour#7]
Relates to #6 #3 

After you view the list of events on the `/schedule` page, click through for more details based on the event id  `/event/id`

- List all registered players
- Event details such as blind structure
- Results
- Rankings

Some ideas

<img width="867" alt="image" src="https://github.com/bitcoinbrisbane/bitcoinpokertour/assets/8411406/149e668e-6526-446e-be19-e6a095c9dfa6">

**Comment by ManyRios** [comment]
Fixed in PR https://github.com/bitcoinbrisbane/bitcoinpokertour/pull/52
